services:
  # Backend Service
  - type: web
    name: stroke-recovery-backend
    env: python
    region: ohio
    buildCommand: "./render-build.sh"
    startCommand: "gunicorn main:app -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: MONGO_DETAILS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
