services:
  # Backend Service
  - type: web
    name: stroke-recovery-backend
    env: docker
    region: ohio
    dockerCommand: "gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    envVars:

      - key: MONGO_DETAILS
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60
